site_name: Simple Site
site_url: https://tententwentytwenty.us
site_description: A simple site for tententwentytwenty
theme:
  name: material
  palette:
    primary: light blue
    accent: orange
    scheme: slate
plugins:
  - search
  - tags
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
